### ISSUE TITLE
About perform_val in training

### ISSUE THREAD

**Issue by RealNewNoob** [sstzal/STAR-FC#12]
Hi! I am checking the train_gcn.py and noticed something weird.
In line 32 `def perform_val()` the `test_inst_num` is defined as the length of `test_idx2lb`, which is the total number of samples in the test set. However, the `pair_a` and `pair_b` are defined as lists of k duplicates of each sample and their k nearest neighbors. When looping over the patches, the `patch_size` is defined as `patch_size = int(test_int_num/patch_num)`. It seems the loop only covers a total of sample size, instead of k times of the sample size, which is the total number of pairs. Does this mean only the initial portions of `pair_a` and `pair_b` are evaluated? The `average_acc` is also obtained by dividing `sum_acc` and `test_inst_num`, which is only a portion of pair a and pair b. 
Another question is why only test the pair-wise accuracy on the knn pairs instead of all pairs? The knn pairs are selected since they are close to each other, won't this cause bias since they are very likely to from the same cluster?

**Comment by sstzal** [comment]
Thanks for your correction！ Fortunately, this is only used to observe the effect on the test set during training. For a more professional test， please refer to here[https://github.com/sstzal/STAR-FC/blob/cd87f97150e7eb8ff9595100226d5b54132d96ac/test_final.py](url).

**Comment by sstzal** [comment]
Thanks for your correction！ Fortunately, this is only used to observe the effect on the test set during training. For a more professional test， please refer to here[https://github.com/sstzal/STAR-FC/blob/cd87f97150e7eb8ff9595100226d5b54132d96ac/test_final.py](url).
