### ISSUE TITLE
To much samples 

### ISSUE THREAD

**Issue by 1017549629** [sstzal/STAR-FC#14]
![image](https://user-images.githubusercontent.com/27629314/127424417-81e9afaf-aecb-47cc-a414-b4925e4e8a90.png)
Hi, I followed your example, didn't change the parameters, just replaced the dataset, and then I was reminded that the number of samples is too large, how can I fix it?

**Comment by sstzal** [comment]
This is because your dataset has too many images per class. Just reduce the sampled clusters and this issue can be fixed.
