### ISSUE TITLE
why bcubed  fscore is so pool?

### ISSUE THREAD

**Issue by xiangliu886** [sstzal/STAR-FC#18]
I test ms1m part1_test.bin with the model you provided. The result:
[Time] evaluate with pairwise consumes 0.0512 s
ave_pre: 0.9559, ave_rec: 0.8870, fscore: 0.9202
[Time] evaluate with bcubed consumes 20.8486 s
ave_pre: 0.0858, ave_rec: 1.0000, fscore: 0.1581
[Time] evaluate with nmi consumes 0.1714 s
nmi: 0.9738

**Comment by sstzal** [comment]
I have not encountered this problem. Usually, the results of these three indicators should not have such a big difference. Can you check your settings or code?
