### ISSUE TITLE
What is `cfg.cluster_num` ?

### ISSUE THREAD

**Issue by RHxW** [sstzal/STAR-FC#3]
Hi ,congratulations to your work!
Got some questions , maybe you could help? Thanks!
1. What is `cfg.cluster_num` ? 
2. Is it the `N` in paper's Algorithms 1?
3. Why added by 200 in `train_gcn.py` line 143

**Comment by sstzal** [comment]
> Hi ,congratulations to your work!
> Got some questions , maybe you could help? Thanks!
> 
> 1. What is `cfg.cluster_num` ?
> 2. Is it the `N` in paper's Algorithms 1?
> 3. Why added by 200 in `train_gcn.py` line 143

For the question 2, YES, you are right. There are a bit differences between the code and the paper. In the code, the M in Algorithms 1 can be seen as 1.
For the question 3, this is the "SR" (sample randomness) in Algorithms 1.
