### ISSUE TITLE
in train_gcn.py,  168line, why "create knn for this batch"? I think the process is  redundant. Can you explain the reason?

### ISSUE THREAD

**Issue by hx121071** [sstzal/STAR-FC#5]

**Comment by sstzal** [comment]
> _No description provided._

Search the corresponding KNN sub-graph from the original whole KNN garph is inconvenient and time-consuming.

**Comment by hx121071** [comment]
> > _No description provided._
> 
> Search the corresponding KNN sub-graph from the original whole KNN garph is inconvenient and time-consuming.

Thank you, I get it. Can I ask you another question, the build-knn process you use "faiss"  or "faiss _gpu" as knn_method? When I use the "faiss" method, the training process is so slow.

**Comment by sstzal** [comment]
> > > _No description provided._
> > 
> > 
> > Search the corresponding KNN sub-graph from the original whole KNN garph is inconvenient and time-consuming.
> 
> Thank you, I get it. Can I ask you another question, the build-knn process you use "faiss" or "faiss _gpu" as knn_method? When I use the "faiss" method, the training process is so slow.

I use faiss for the MS1M and faiss_gpu for the WebFace42M. Yep, the training time for a whole epoch is very long, however, the network will converge before a whole epoch.
