### ISSUE TITLE
There is a problem when running with test_final.py

### ISSUE THREAD

**Issue by GlennCGL** [sstzal/STAR-FC#8]
Traceback (most recent call last):
  File "test_final.py", line 167, in <module>
    gt_labels = np.load('./pretrained_model/gt_labels.npy')
  File "/mnt/lustre/caoguoliang1/anaconda3/envs/cluster/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './pretrained_model/gt_labels.npy'

What is gt_labels.npy?

**Comment by whoNamedCody** [comment]
> Traceback (most recent call last):
> File "test_final.py", line 167, in
> gt_labels = np.load('./pretrained_model/gt_labels.npy')
> File "/mnt/lustre/caoguoliang1/anaconda3/envs/cluster/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
> fid = stack.enter_context(open(os_fspath(file), "rb"))
> FileNotFoundError: [Errno 2] No such file or directory: './pretrained_model/gt_labels.npy'
> 
> What is gt_labels.npy?

So, how to deal the problem?

**Comment by Govan111** [comment]
Hello, I also meet with this problems. Is there a solution to this problem?

**Comment by YuetianW** [comment]
I also meet with this problems. Is there a solution to this problem?
