### ISSUE TITLE
Inference time comparison between GCNV and starfc

### ISSUE THREAD

**Issue by marigoold** [sstzal/STAR-FC#9]
In Table 4, the inference time of starfc is 310s, which is faster than GCN-V+E 609s. But did you compare the inference time between starfc and gcnv (without gcn-e part)? Which one is faster?
In my experiments, the accuracy of GCN-V is high enough. And the inference time of GCN-E takes up most of the inference time of GCN-V+E. So in most scenarios, GCN-E is not needed.

**Comment by sstzal** [comment]
Yep,  the inference time of GCN-V in their paper is 4.5m (270s). You can also run their code, the authors make a good open source. Their inference with only GCN-V is faster than the STAR-FC, however, there is a gap in the accuracy.
